In [22]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from scipy.ndimage.interpolation import shift

In [89]:
# binomial options pricing method
n = 15  # periods
T = 0.25 # maturity 3 months
S0 = 100 # price at t0
K = 110 # strike price
r = 1+ 2/100. #risk-free interest rate
sigma = 30/100. # volatility
c = 1/100. #dividend yield
u = 1.0395 
d = 1./u
q = (r-d)/(u-d)



In [90]:
# u=1.06
# d = 1./u
# q = (r-d)/(u-d)
1/r *(16.167*q + (1-q)*6.76)

13.529458861352762

In [81]:
pricetree = np.zeros((n,n))
for i in range(n):
    S_n = S0*u**i
    pricetree += np.diag(S_n*d**np.arange(0,n-i),k=i)
    

In [87]:
C_n = np.zeros((n,n))
zeros = np.zeros((n))
C_n[:,n-1] = np.max(np.array([pricetree[:,(n-1)] - K,zeros]),axis=0)
for j in range(n-1):
    C_n_aux = shift(C_n[:,n-1-j],-1,cval=0)
    C_n[:,n-2-j] = np.round(1/r *(C_n[:,n-1-j]*q + (1-q)*C_n_aux),4)
    
    print(j)
    
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13


In [88]:
pd.DataFrame(C_n)

0        1        2        3        4        5        6        7   \
0   17.1184  19.2371  21.5210  23.9698  26.5822  29.3570  32.2935  35.3921   
1   10.5577  12.1775  13.9730  15.9483  18.1049  20.4419  22.9564  25.6441   
2    5.5172   6.5793   7.8052   9.2087  10.8016  12.5929  14.5878  16.7870   
3    2.2533   2.7966   3.4561   4.2513   5.2029   6.3324   7.6606   9.2064   
4    0.6288   0.8164   1.0574   1.3658   1.7587   2.2569   2.8851   3.6720   
5    0.0886   0.1208   0.1646   0.2243   0.3057   0.4166   0.5678   0.7739   
6    0.0000  -0.0000   0.0000   0.0000  -0.0000  -0.0000   0.0000  -0.0000   
7    0.0000   0.0000  -0.0000  -0.0000   0.0000  -0.0000  -0.0000   0.0000   
8    0.0000  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000   
9    0.0000  -0.0000   0.0000   0.0000  -0.0000  -0.0000   0.0000   0.0000   
10   0.0000  -0.0000  -0.0000  -0.0000  -0.0000   0.0000   0.0000   0.0000   
11  -0.0000  -0.0000  -0.0000  -0.0000   0.0000   0.0000   0.0000  -0.0000   
12   0.0000   0.0000   0.0000  -0.0000   0.0000   0.0000   0.0000  -0.0000   
13  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000   
14   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   

         8        9        10       11       12       13         14  
0   38.6550  42.0861  45.6913  49.4778  53.4534  57.6265  62.005729  
1   28.5006  31.5224  34.7085  38.0611  41.5858  45.2901  49.181988  
2   19.1865  21.7783  24.5516  27.4955  30.6029  33.8734  37.314310  
3   10.9844  13.0028  15.2608  17.7469  20.4388  23.3078  26.331417  
4    4.6500   5.8543   7.3203   9.0793  11.1508  13.5300  16.167344  
5    1.0548   1.4376   1.9593   2.6704   3.6396   4.9606   6.761045  
6   -0.0000   0.0000  -0.0000  -0.0000   0.0000  -0.0000   0.000000  
7   -0.0000   0.0000  -0.0000  -0.0000   0.0000   0.0000   0.000000  
8   -0.0000  -0.0000   0.0000  -0.0000   0.0000   0.0000   0.000000  
9   -0.0000  -0.0000  -0.0000  -0.0000   0.0000  -0.0000   0.000000  
10  -0.0000  -0.0000   0.0000  -0.0000  -0.0000   0.0000   0.000000  
11  -0.0000  -0.0000   0.0000  -0.0000   0.0000   0.0000   0.000000  
12   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.000000  
13  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000  -0.0000   0.000000  
14   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.000000

In [74]:
S

0           1           2           3           4           5   \
0   100.0  103.950000  108.056025  112.324238  116.761045  121.373107   
1     0.0   96.200096  100.000000  103.950000  108.056025  112.324238   
2     0.0    0.000000   92.544585   96.200096  100.000000  103.950000   
3     0.0    0.000000    0.000000   89.027980   92.544585   96.200096   
4     0.0    0.000000    0.000000    0.000000   85.645002   89.027980   
5     0.0    0.000000    0.000000    0.000000    0.000000   82.390575   
6     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
7     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
8     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
9     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
10    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
11    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
12    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
13    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
14    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   

            6           7           8           9           10          11  \
0   126.167344  131.150954  136.331417  141.716508  147.314310  153.133226   
1   116.761045  121.373107  126.167344  131.150954  136.331417  141.716508   
2   108.056025  112.324238  116.761045  121.373107  126.167344  131.150954   
3   100.000000  103.950000  108.056025  112.324238  116.761045  121.373107   
4    92.544585   96.200096  100.000000  103.950000  108.056025  112.324238   
5    85.645002   89.027980   92.544585   96.200096  100.000000  103.950000   
6    79.259812   82.390575   85.645002   89.027980   92.544585   96.200096   
7     0.000000   76.248015   79.259812   82.390575   85.645002   89.027980   
8     0.000000    0.000000   73.350664   76.248015   79.259812   82.390575   
9     0.000000    0.000000    0.000000   70.563410   73.350664   76.248015   
10    0.000000    0.000000    0.000000    0.000000   67.882068   70.563410   
11    0.000000    0.000000    0.000000    0.000000    0.000000   65.302615   
12    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
13    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
14    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   

            12          13          14  
0   159.181988  165.469676  172.005729  
1   147.314310  153.133226  159.181988  
2   136.331417  141.716508  147.314310  
3   126.167344  131.150954  136.331417  
4   116.761045  121.373107  126.167344  
5   108.056025  112.324238  116.761045  
6   100.000000  103.950000  108.056025  
7    92.544585   96.200096  100.000000  
8    85.645002   89.027980   92.544585  
9    79.259812   82.390575   85.645002  
10   73.350664   76.248015   79.259812  
11   67.882068   70.563410   73.350664  
12   62.821178   65.302615   67.882068  
13    0.000000   60.434034   62.821178  
14    0.000000    0.000000   58.137599

In [78]:
pricetree[(pricetree -110)>0]

array([112.36      , 119.1016    , 126.247696  , 133.82255776,
       141.85191123, 150.3630259 , 159.38480745, 168.9478959 ,
       179.08476965, 189.82985583, 201.21964718, 213.29282601,
       226.09039558, 112.36      , 119.1016    , 126.247696  ,
       133.82255776, 141.85191123, 150.3630259 , 159.38480745,
       168.9478959 , 179.08476965, 189.82985583, 201.21964718,
       112.36      , 119.1016    , 126.247696  , 133.82255776,
       141.85191123, 150.3630259 , 159.38480745, 168.9478959 ,
       179.08476965, 112.36      , 119.1016    , 126.247696  ,
       133.82255776, 141.85191123, 150.3630259 , 159.38480745,
       112.36      , 119.1016    , 126.247696  , 133.82255776,
       141.85191123, 112.36      , 119.1016    , 126.247696  ,
       112.36      ])

In [79]:
(pricetree -110)>0

array([[False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, Fa

In [20]:
S = pd.DataFrame(pricetree)

In [21]:
S

0           1           2           3           4           5   \
0   100.0  103.950000  108.056025  112.324238  116.761045  121.373107   
1     0.0   96.200096  100.000000  103.950000  108.056025  112.324238   
2     0.0    0.000000   92.544585   96.200096  100.000000  103.950000   
3     0.0    0.000000    0.000000   89.027980   92.544585   96.200096   
4     0.0    0.000000    0.000000    0.000000   85.645002   89.027980   
5     0.0    0.000000    0.000000    0.000000    0.000000   82.390575   
6     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
7     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
8     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
9     0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
10    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
11    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
12    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
13    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   
14    0.0    0.000000    0.000000    0.000000    0.000000    0.000000   

            6           7           8           9           10          11  \
0   126.167344  131.150954  136.331417  141.716508  147.314310  153.133226   
1   116.761045  121.373107  126.167344  131.150954  136.331417  141.716508   
2   108.056025  112.324238  116.761045  121.373107  126.167344  131.150954   
3   100.000000  103.950000  108.056025  112.324238  116.761045  121.373107   
4    92.544585   96.200096  100.000000  103.950000  108.056025  112.324238   
5    85.645002   89.027980   92.544585   96.200096  100.000000  103.950000   
6    79.259812   82.390575   85.645002   89.027980   92.544585   96.200096   
7     0.000000   76.248015   79.259812   82.390575   85.645002   89.027980   
8     0.000000    0.000000   73.350664   76.248015   79.259812   82.390575   
9     0.000000    0.000000    0.000000   70.563410   73.350664   76.248015   
10    0.000000    0.000000    0.000000    0.000000   67.882068   70.563410   
11    0.000000    0.000000    0.000000    0.000000    0.000000   65.302615   
12    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
13    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
14    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   

            12          13          14  
0   159.181988  165.469676  172.005729  
1   147.314310  153.133226  159.181988  
2   136.331417  141.716508  147.314310  
3   126.167344  131.150954  136.331417  
4   116.761045  121.373107  126.167344  
5   108.056025  112.324238  116.761045  
6   100.000000  103.950000  108.056025  
7    92.544585   96.200096  100.000000  
8    85.645002   89.027980   92.544585  
9    79.259812   82.390575   85.645002  
10   73.350664   76.248015   79.259812  
11   67.882068   70.563410   73.350664  
12   62.821178   65.302615   67.882068  
13    0.000000   60.434034   62.821178  
14    0.000000    0.000000   58.137599

In [ ]:
# pricetree = np.zeros((n,n))
# pricetree[0,:] = S0*u**np.arange(0,n)
# np.fill_diagonal(pricetree,S0*d**np.arange(0,n))
# # pricetree = 

In [20]:
66*1.5

99.0

In [21]:
66.66666666666667*1.5

100.0

In [22]:
a = np.array([1,2,3])

In [23]:
4**a

array([ 4, 16, 64])

In [6]:
112.36-95

17.36

In [41]:
print(a)

None


In [46]:
pricetree

array([[100.        , 103.95      , 108.056025  , 112.32423799,
        116.76104539, 121.37310668, 126.16734439, 131.1509545 ,
        136.3314172 , 141.71650818, 147.31431025, 153.13322551,
        159.18198792, 165.46967644, 172.00572866],
       [  0.        ,  96.2000962 ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,  92.54458509,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,  89.02797988,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,   0.  

In [47]:
x = np.arange(9).reshape((3,3))

In [52]:
np.diag([1],k=15)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])